pipeline {
  agent any
  stages {
    stage("Build") {
      steps {
        echo " echo pipelineConfig.message " 
        build()
      }
    }
    stage("Analysis") {
      steps {
        echo "234"
        static_code_analysis()    
      }
    }
    
    
    
  }
}
